---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj13-ryanj13-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/ryanj13-gateway-gitops
